### ISSUE TITLE
gulp build issue when Node 13.X

### ISSUE THREAD

**Issue by pavan2106** [OctopusDeploy/octofxjs#1]
Hi Team, 

When node in our machine is 13.x, gulp task is failing. We required to update gulp 4.x. Also has to correct the gulp.js file as below. FYI,As I don't have access to push my changes. 

```
gulp.task('build', gulp.parallel('less', 'scripts'));

gulp.task('default', gulp.parallel('less', 'scripts'), function() {
  gulp.watch('./src/less/**/*.less', ['less']);
  gulp.watch(['./src/js/vendor/**/*.js', './src/js/app/**/*.js'], ['scripts']);
});

```
Thanks,
Pavan

**Comment by pstephenson02** [comment]
Hi @pavan2106. I just tested running this app on node 13.x and 14.x. Both seemed to build and run successfully. Also, I'm a little confused by your issue because there is no gulp build process (or gulpfile) defined in the project. Can you provide some more info about your issue? Thanks.

**Comment by pavan2106** [comment]
Hi Phil,

Sorry, I forgot to share additional information , I have referred details
from the URL:
https://octopus.com/docs/deployment-examples/node-deployments/node-on-linux.
and opted Option 1. Below is the error message. Please let me know if
you need more details.

[image: image.png]


Regards
Kota Pavan Kumar

**Comment by BobJWalker** [comment]
Updated with recommended changes
